### PR TITLE
Fixed Gauss documentation

### LINKED ISSUE #192: Incompatibility between Gauss and MatricesForHomalg
In GAP distribution tests we require that `LoadAllPackages();` and `LoadAllPackages(:reversed);` should work. Of course, it is not practical to load all packages in a GAP session, but it's a useful exercise to find incompatibilities between projects. We recommend package authors to do that when they test their package. Also, if your package have standard test (by "standard" I mean a test file specified in `PackageInfo.g`) then `make testpackage PKGNAME=pkgname` (where `pkgname` is the name of the tested package) would run its test three times: without/with all/with default packages. So you would also be able to the a problem if loading all packages does not work.

This morning, new packages from the homalg project were picked up, and Jenkins tests reported incompatibilities within packages from the homalg project itself. Dependently on the order in which packages are loaded, the following errors happen:

```
#I  Gauss: entering LoadPackage 
#I  Gauss: PackageAvailabilityInfo for version 2017.12.07
#I  Gauss: PackageAvailabilityInfo: the AvailabilityTest function returned 'true'
#I  Gauss: PackageAvailabilityInfo: no needed packages
#I  Gauss: PackageAvailabilityInfo: check suggested packages
#I         GAPDoc (>= 1.0)
#I  Gauss: PackageAvailabilityInfo: check of suggested packages done
#I  Gauss: PackageAvailabilityInfo: version 2017.12.07 is available
#I  Gauss: start loading needed/suggested/self packages
#I         gauss
#I  Gauss: start reading file 'init.g'
Error, variable `UnionOfRows' is not bound to an operation at /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest/GAPCO\
PTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovacs/GAP-pkg-update-stab\
le-snapshot/lib/oper.g:773 called from
```

or 

```
#I  MatricesForHomalg: start reading file 'init.g'
Error, BIND_GLOBAL: variable `UnionOfRows' must be unbound at /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest/GAPCO\
PTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovacs/GAP-pkg-update-stab\
le-snapshot/lib/global.g:137 called from
```

This is a severe issue - unless you could provide a quick fix, I will need to exclude a package from testing to restore the tests. Perhaps disabling Gauss will be enough.

### PR DESCRIPTION
**Pull request by sebasguts**
This closes #192 once Gauss is released

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
This only updates the documentation, but the error in #192 is happening when packages are loaded. I can't see why this fix will work. Or do I miss something?

**Comment by sebasguts** [comment]
Yep. The appropriate version of Gauss was not released because of errors in the manual build.

**Comment by mohamed-barakat** [comment]
Thanks, I fixed this already in ad550de.

**Comment by sebasguts** [comment]
:D

**Comment by mohamed-barakat** [comment]
Sorry, this was `GaussForHomalg`.

**Comment by olexandr-konovalov** [comment]
@mohamed-barakat Although the fix is in `GaussForHomalg/gap/GaussTools.gi` in a different way. Trust that it works. Can you then make a release ASAP?

**Comment by sebasguts** [comment]
Thought you alread noticed when you reopened :).

**Comment by mohamed-barakat** [comment]
@sebasguts: Thanks :)
@alex-konovalov: Done!

**Pull request merged**
